### ISSUE TITLE
Facebook authentication is not working on a fresh install.

### ISSUE THREAD

**Issue by n370** [heroku/nibs#6]
I just cloned the project and worked through this [guide](https://heroku.github.io/nibs/setup.html) to get it working locally. Unfortunately as soon as I clicked the "login with facebook" button this is what I got.

Any clue?

![](http://i.imgur.com/WSDZ1D2.png)

**Comment by chrisanderton** [comment]
Does your Contact table have a fbUserId__c column?

**Comment by n370** [comment]
@chrisanderton

It seems it doesn't Chris.

![](http://i.imgur.com/aSHWEWR.png)

**Comment by chrisanderton** [comment]
Ok - if you look here [line 78, Facebook.js](https://github.com/heroku/nibs/blob/master/server/facebook.js#L78) you will see the columns it is trying to insert into.

I think the problem is that these columns are created when you use Heroku Connect to connect to Salesforce - they are not currently created for you when using in isolation.

If you add the following two columns to your Contact table (the data types in brackets are what i am pulling out from a db i have here - i don't know why gender needs 255 chars max!):

fbUserId__c (varchar, max 50)
gender__c (varchar max 255)

And then try it..

**Comment by n370** [comment]
Thanks @chrisanderton! It's working fine now. 
I just had to make sure **column names were all lowercase**.
